Fix the build without XSync extension enabled
When trying to build muffin with `--disable-xsync` option, it fails for
a variety of reasons:

```
compositor/meta-window-actor.c:1292:44: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_serial'
 1292 |   frame->sync_request_serial = priv->window->sync_request_serial;
```

```
core/window.c: In function 'meta_window_unmanage':
core/window.c:1865:13: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_timeout_id'
 1865 |   if (window->sync_request_timeout_id)
      |             ^~
core/window.c:1867:30: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_timeout_id'
 1867 |       g_source_remove (window->sync_request_timeout_id);
      |                              ^~
core/window.c:1868:13: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_timeout_id'
 1868 |       window->sync_request_timeout_id = 0;
      |             ^~
```

```
core/window-props.c:1143:15: error: 'MetaWindow' {aka 'struct _MetaWindow'} has no member named 'sync_request_counter'; did you mean 'extended_sync_request_counter'?
 1143 |       window->sync_request_counter = None;
      |               ^~~~~~~~~~~~~~~~~~~~
```

This seems to be due to missing `HAVE_XSYNC` macro checks. Adding these
checks where appropriate to make sure that muffin can be built.